### PR TITLE
uplift go example

### PR DESCRIPTION
**Pull request by matoszz**
- updates license (copied from https://github.com/resend/react-email)
- updates README with correct resend-go/v2 version
- updates example with resend-go/v2
- updates Renovate.json
- changes file from index.go to main.go for consistency / sanity

### CODE REVIEW

**Comment by drish** [comment]
thanks for the PR 👍

**Review by bukinoshita — APPROVED** [review]

**Comment by drish** [comment]
@matoszz just one thing, could you update `main.go` to import from `"github.com/resend/resend-go/v2"` instead of `github.com/resendlabs/resend-go` ?

**Comment by matoszz** [comment]
@drish of course; good catch - updated the import and cleaned up the previous import via `go mod tidy`

**Review by drish — APPROVED** [review]

**Comment by matoszz** [comment]
@drish you have to merge this PR as I don't have permissions to do so

**Pull request merged**
